# Frontend Dockerfile

# Use an official Node.js runtime as a parent image
FROM node:18-alpine AS frontend

# Set the working directory for the frontend
WORKDIR /app/frontend

# Copy frontend package and install dependencies
COPY package*.json ./

RUN npm install

# Copy the rest of the frontend code
COPY . .

# Set environment variables
ENV PORT=3002

# Expose the frontend port
EXPOSE 3002

# Run the frontend app
CMD ["npm", "start"]
