# Use an official Node.js runtime as a parent image
FROM node:18-alpine AS frontend

# Set the working directory for the frontend
WORKDIR /app/frontend

# Copy frontend package and install dependencies
COPY package*.json ./

# Install packages
RUN npm install

# Install serve globally
RUN npm install -g serve

# Copy the rest of the frontend code
COPY . .

# Set environment variables
ENV PORT=3002
ARG REACT_APP_BACKEND_URL

ENV REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL

# Build the app
RUN npm run build

# Expose the frontend port
EXPOSE 3002

# Run the frontend app
CMD ["serve", "-s", "build", "--ssl-cert", "/etc/letsencrypt/live/app.yisraelberman.com/fullchain.pem", "--ssl-key", "/etc/letsencrypt/live/app.yisraelberman.com/privkey.pem", "--listen", "3002"]