version: '3'

services:
  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
    ports:
      - "8443:8443"
    volumes:
      - /etc/letsencrypt/live/keycloak.yisraelberman.com/fullchain.pem:/etc/x509/https/tls.crt:ro
      - /etc/letsencrypt/live/keycloak.yisraelberman.com/privkey.pem:/etc/x509/https/tls.key:ro
    depends_on:
      - postgres
    command:
      - start
    networks:
      - keycloak-network

volumes:
  postgres_data:

networks:
  keycloak-network: