version: '3'

services:
  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: "false"           #for http
      KC_HOSTNAME_STRICT_HTTPS: "false"         #for http
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command:
      - start-dev
      - --http-enabled=true           #for http
      - --hostname-strict=false          #for http
      - --hostname-strict-https=false           #for http
    networks:
      - keycloak-network

volumes:
  postgres_data:

networks:
  keycloak-network: