# Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Set the working directory
WORKDIR /app/admin-frontend

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Install serve globally
RUN npm install -g serve

# Copy all application files
COPY . .

# Set environment variables
ENV PORT=3001
ARG REACT_APP_API_BASE_URL
ENV REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL

# Build the app
RUN npm run build

# Expose the port
EXPOSE 3001

# Start the app using serve
CMD ["serve", "-s", "build", "--ssl-cert", "/etc/letsencrypt/live/app.yisraelberman.com/fullchain.pem", "--ssl-key", "/etc/letsencrypt/live/app.yisraelberman.com/privkey.pem", "--listen", "3001"]



