version: '3'

services:
  backend:
    image: app-backend
    environment:
      - FLASK_ENV=production
    ports:
      - "5000:5000"

  frontend:
    image: app-frontend
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    ports:
      - "3002:3002"


# sudo REACT_APP_BACKEND_URL=http://<ip>:5000 docker-compose up
