# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Install gunicorn
RUN pip install gunicorn

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variables with default values
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV KEYCLOAK_URL=https://keycloak.yisraelberman.com
ENV KEYCLOAK_REALM=my-app-realm
ENV KEYCLOAK_CLIENT_ID=my-app-client
ENV CORS_ORIGIN=https://app.yisraelberman.com

# Run gunicorn with SSL support when the container launches
CMD ["gunicorn", "--certfile", "/etc/letsencrypt/live/app.yisraelberman.com/fullchain.pem", "--keyfile", "/etc/letsencrypt/live/app.yisraelberman.com/privkey.pem", "-b", "0.0.0.0:5000", "app:app"]