name: SQS Trigger
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  send-to-sqs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Send message to SQS
      run: |
        # For pull requests, use the head branch name
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          BRANCH="${{ github.head_ref }}"
        else
          # For pushes, extract branch name from ref and decode URL encoding
          BRANCH="${GITHUB_REF#refs/heads/}"
          BRANCH=$(echo "$BRANCH" | sed 's/%2F/\//g')  # Replace %2F with /
        fi
        
        aws sqs send-message \
          --queue-url ${{ secrets.SQS_QUEUE_URL }} \
          --message-body '{
            "project": "${{ github.repository }}",
            "commit_message": "${{ github.event.head_commit.message }}",
            "event_type": "${{ github.event_name }}",
            "branch": "'"$BRANCH"'"
          }'